### ISSUE TITLE
Refactor 1.2 tests to avoid transferring of state

### ISSUE THREAD

**Issue by ksgeorgieva** [finos/FDC3-conformance-framework#127]
The following issues found while running test with Glue42 implementation of FDC3:

| method | problem | proposed fix |
| --- | --- | --- |
| `broadcast` |  |  | 
| | System Channels - the same context type is broadcasted in each test | Add postfix as ID in type and send it to the support app (ex: "fdc3.client.4242") |
| | App Channels - broadcast always on the same channel | Create new app channel in each test and pass its name to the support app |
| `open` | Tests `AOpensBNoListen` and `AOpensBWithWrongContext` are insufficient with FDC3 1.2 spec | Remove tests |
| `joinChannel` |  |  |
| | `BasicJC1` - context messages broadcast to a channel by an application joined to it should **NOT** be delivered back to that same application | Refactor test |

**Comment by kriswest** [comment]
resolved
