### ISSUE TITLE
Open API Test Cases

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3-conformance-framework#18]
## A Opens B

- `AOpensB1`: [ ] **A** calls `fdc3.open(‘app B Name’)`, check app **B** opens
- `AOpensB1`: [ ] **A** calls `fdc3.open({name: “<app B Name>”})`, check app **B** opens
- `AOpensB1`:  [ ] **A** calls `fdc3.open({name: “<app B Name>”, appId: “<app B ID”})`, check app **B** opens
- `AOpensB1`:  [ ] **A** calls `{appID: “<app ID>”}, check app **B** opens.  (`FDC3 2.0`)

## A Fails To Open B

- `AFailsToOpenB`:  Run the above 4 tests again with a non-existent app name/app id.  Should return “App Not Found” Error from https://fdc3.finos.org/docs/api/ref/Errors#openerror

## A Opens B With Context

| App | Step            | Description                                              |
|-----|-----------------|----------------------------------------------------------|
| A   | Opening App     | various open methods as in `AOpensB1` except with a `<context>` argument <br>check app opens    |
| B   | Context present | `fdc3.addContextListener()`<br>- receives `<context>` from **A** |

- [ ] `AOpensBWithContext`: Perform above tests
- [ ] `AOpensBWithSpecificContext`: Perform above but replace **B**s call with `fdc3.addContextListener('fdc3.instrument`)`

## Specific Context

| App | Step            | Description                                                                                                                   |
|-----|-----------------|-------------------------------------------------------------------------------------------------------------------------------|
| A   | Opening App     | `fdc3.open(‘app Name’, <contact context>)` <br>check app opens                                                                |
| B   | Context present | fdc3.addContextListener()<br>- receives <context> from a                                                                      |
| A   | Promise         | - receives a rejection from the open promise with “App Timeout’ from <br>https://fdc3.finos.org/docs/api/ref/Errors#openerror |

- [ ] `AOpensBWithWrongContext`: As above
- [ ] `AOpensBNoListen`: Skip `fdc3.addContextListener() above. 
- [ ] `AOpensBMultipleListen`:  **B** performs `fdc3.addContextListener('fdc3.instrument') prior to the existing `addContextListener`.  The correct context listener should receive the context, and the promise completes successfully
- [ ] `AOpensBMalformedContext`: **A** tries to pass malformed context to **B**.  Context listener receives nothing, promise completes successfully.

**Comment by osouthwell-scottlogic** [comment]
@robmoffat Hi, is it possible to have this issue assigned to me?

**Comment by ColinEberhardt** [comment]
This has been partially implemented in https://github.com/finos/FDC3-conformance-framework/pull/49 - we do have a big obstacle, how do you verify that a given app was opened and (optionally) context received. We'll look into various ways we can confirm this in an automated fashion.

**Comment by ColinEberhardt** [comment]
We now verify the communication from app to mock-app, via https://github.com/finos/FDC3-conformance-framework/pull/51 - so this issue is resolved.
