### ISSUE TITLE
Create NPM Module for the Tests

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3-conformance-framework#188]
This was requested by @ksgeorgieva so that they could add the conformance tests to their CI/CD pipeline

**Comment by robmoffat** [comment]
@TheJuanAndOnly99 might be able to help @gaganahluwalia with this when it comes time to implement

**Comment by kriswest** [comment]
We'd  support the idea of an NPM module for the tests - we're currently checking them out (from a local fork) in our CI system. The module should include the directory entries for localhost and would need the httpserver script internalising as a function to run it.

Alternatively, a hosted set of the conformance apps would also work just fine - but runs into to trouble with the customisations to load proprietary libs... But then so does an NPM module without some additional work.

**Comment by robmoffat** [comment]
let's talk about this next week

**Comment by robmoffat** [comment]
We should add tests to FDC3-Sail to use this once it's published (via GitHub actions)
