### ISSUE TITLE
Incorrect test definitions

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3-conformance-framework#72]
Our first review of the tests turned up some incorrectly defined tests. 

## Incorrectly defined tests
(So far I haven't found the below in the issues raised with test cases, hence, they may have been added during implementation. In one case this could be an area that the standard could improve, but doesn't currently cover (and hence can't be part of a compliance test).

### 1)
https://github.com/finos/FDC3-conformance-framework/blob/cd8969bb0b7adff6f4d52fc02094e3b129995a4c/tests/src/test/fdc3.broadcast.ts#L117

This directly contradicts the Standard: [Joining User Channels in 2.0](https://fdc3.finos.org/docs/api/spec#joining-user-channels) and [Joining Channels in 1.2](https://fdc3.finos.org/docs/1.2/api/spec#joining-channels):
>If an app is not joined to a User channel [fdc3.broadcast](https://fdc3.finos.org/docs/api/ref/DesktopAgent#broadcast) will be a no-op and handler functions added with [fdc3.addContextListener](https://fdc3.finos.org/docs/api/ref/DesktopAgent#addcontextlistener) will not receive any broadcasts.

Remove this test please.

### 2)
https://github.com/finos/FDC3-conformance-framework/blob/cd8969bb0b7adff6f4d52fc02094e3b129995a4c/tests/src/test/fdc3.broadcast.ts#L376

No such error exists in FDC3 1.2 or 2.0. See https://fdc3.finos.org/docs/1.2/api/ref/Errors

There is at present no statement of what should or should not happen when an invalid context object is passed. What is known is that it would not be delivered to a filtered context listener without a type, but that is all that's specified.

Remove this test please - or at least comment it out with a note that its not defined in the standard.

### 3)
https://github.com/finos/FDC3-conformance-framework/blob/cd8969bb0b7adff6f4d52fc02094e3b129995a4c/tests/src/test/fdc3.broadcast.ts#L696

No such error exists in FDC3 1.2 or 2.0. See https://fdc3.finos.org/docs/1.2/api/ref/Errors

Remove this test please - or at least comment it out with a note that its not defined in the standard.

### 4)
https://github.com/finos/FDC3-conformance-framework/blob/cd8969bb0b7adff6f4d52fc02094e3b129995a4c/tests/src/test/fdc3.broadcast.ts#L738

You didn't wait for it to do its broadcasts here as you do in other tests:
https://github.com/finos/FDC3-conformance-framework/blob/cd8969bb0b7adff6f4d52fc02094e3b129995a4c/tests/src/test/fdc3.broadcast.ts#L749-L757

This is an example of a place where coordinating messages could be used instead of waits... see [Implementation feedback #74](https://github.com/finos/FDC3-conformance-framework/issues/74).

### 5)
https://github.com/finos/FDC3-conformance-framework/blob/cd8969bb0b7adff6f4d52fc02094e3b129995a4c/tests/src/test/fdc3.open.ts#L101

This test should/will never pass as the (malformed) context has no type, so it can't be routed to a typed context listener. Perhaps better to confirm it did get started by another means... However, behaviour with an invalid argument is not defined in the standard. Hence, I'd probably just go ahead and remove this test.

### 6)
https://github.com/finos/FDC3-conformance-framework/blob/cd8969bb0b7adff6f4d52fc02094e3b129995a4c/tests/src/test/fdc3.raiseIntent.ts#L86

Note that `IntentResolution.source` is of type [`TargetApp`](https://fdc3.finos.org/docs/1.2/api/ref/Types#targetapp), which can be the string `name` or an `AppMetadata` object. Thats not why Finsemble fails this test - but led me to this error.
Note that this needs fixing in multiple tests in this file.

**Comment by Joe-Dunleavy** [comment]
I've created a PR that addresses these issues:

https://github.com/finos/FDC3-conformance-framework/pull/75

**Comment by ColinEberhardt** [comment]
All addressed in #75
