### ISSUE TITLE
User Channels Test Cases (2.0)

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3-conformance-framework#79]
https://github.com/finos/FDC3/blob/conformance2.0/toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md#2-user-channels

**Comment by kriswest** [comment]
Note I'd very much recommend that you look at build and deployment in the 1.2 version before moving onto 2.0 (lest ye do it twice) ;-)

Will let you know when reviewed/ error checked.

**Comment by robmoffat** [comment]
> look at build and deployment in the 1.2 version

Going to have a chat with @Joe-Dunleavy about it this afternoon

**Comment by Joe-Dunleavy** [comment]
I've finished implementing these, I just need to be able to test them against a desktop agent that implements fdc3 2.0

**Comment by Joe-Dunleavy** [comment]
I've created a draft PR for the app and user test cases: https://github.com/finos/FDC3-conformance-framework/pull/90
