### ISSUE TITLE
Intents Test Cases (2.0)

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3-conformance-framework#81]
please refer to:https://github.com/finos/FDC3/blob/conformance2.0/toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md#6-intents

**Comment by robmoffat** [comment]
Regarding the apps/listensFor part. Isn't it possible to listenFor an intent without specifying contextType?

**Comment by kriswest** [comment]
In the API yes (you can't specify the context type, only the intent, so one listener for the intent type must handle all possible context types). But in the AppD record you do specify context type pairs supported for use in resolution (if you don't specify them you are not offered as a result).

This makes dynamic registration without an appD record (which is optional) a bit off (as you can't filter by context type). But its manageable.
