### ISSUE TITLE
App Channels Test Cases (2.0)

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3-conformance-framework#82]
https://github.com/finos/FDC3/blob/conformance2.0/toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md#3-app-channels

**Comment by robmoffat** [comment]
Ready for implementation @Joe-Dunleavy @ColinEberhardt

**Comment by Joe-Dunleavy** [comment]
f.y.i `AC Basic Usage 2 is not possible` as 1 needs to happen before 2

**Comment by kriswest** [comment]
@Joe-Dunleavy you are correct! It looks like it just didn't get deleted as it was redefined on the next line.

**Comment by Joe-Dunleavy** [comment]
I've finished implementing these, they just need testing

**Comment by Joe-Dunleavy** [comment]
I've created a draft PR for the app and user test cases: https://github.com/finos/FDC3-conformance-framework/pull/90

**Comment by robmoffat** [comment]
closing this.  Please refer to https://github.com/finos/FDC3/blob/conformance2.0/toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
