### ISSUE TITLE
Metadata and Instance test cases (2.0)

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3-conformance-framework#88]
please refer to : https://github.com/finos/FDC3/blob/conformance2.0/toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md#5-metadata--instance-test-cases

**Comment by Joe-Dunleavy** [comment]
I believe `screenshots (Array<Image>)`  in `Setup` should be `images (Array<Image>)`

**Comment by Joe-Dunleavy** [comment]
That's odd -- `fdc3.getAppMetadata({appId: "<A's appId>"})` returns an `AppMetadata` object. The interface it implements does not contain a `screenshots` field but does contain an `images` field.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/107405201/200893454-e1707bd4-8cba-4742-8f33-c02fa84dce2c.png">

Looks like it hasn't been updated from 1.2

When comparing the AppMetadata object to the expected definition
 for the fields provided, I am going to have to leave out `screenshots` as it isn't considered a valid AppMetaData field

**Comment by kriswest** [comment]
We'll look into fixing that in the API types.

**Comment by kriswest** [comment]
PR raised to fix API types in NPM module: 

- https://github.com/finos/FDC3/pull/850

Will try and report back when its merged/released.

**Comment by robmoffat** [comment]
Closing this, please refer to : https://github.com/finos/FDC3/blob/conformance2.0/toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md

**Comment by Joe-Dunleavy** [comment]
A pull request for these tests: https://github.com/finos/FDC3-conformance-framework/pull/120
